"""empty message

Revision ID: 69a1385248e5
Revises: 8f7ca36eeb77
Create Date: 2023-10-10 09:24:19.435044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a1385248e5'
down_revision = '8f7ca36eeb77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fave_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorites_name_key', type_='unique')
        batch_op.drop_constraint('favorites_type_key', type_='unique')
        batch_op.drop_constraint('favorites_url_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('favorites_url_key', ['url'])
        batch_op.create_unique_constraint('favorites_type_key', ['type'])
        batch_op.create_unique_constraint('favorites_name_key', ['name'])
        batch_op.drop_column('fave_id')

    # ### end Alembic commands ###
