"""empty message

Revision ID: 845b15d10040
Revises: 76b7d0f12ae5
Create Date: 2023-10-09 19:21:18.241560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845b15d10040'
down_revision = '76b7d0f12ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_uid', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('birth_year', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
