"""empty message

Revision ID: 8f7ca36eeb77
Revises: d1cc1100a7a2
Create Date: 2023-10-10 08:49:57.044432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7ca36eeb77'
down_revision = 'd1cc1100a7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['type'])
        batch_op.create_unique_constraint(None, ['url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('url')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
